project:
  type: website
  output-dir: docs

website:
  title: "Dun Zhang"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: twitter-x
        href: https://x.com/dunzhangz
      - icon: github
        href: https://github.com/dunzhangz

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



